const state={cart:JSON.parse(localStorage.getItem("aurelia-cart")||"[]")};const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];const money=n=>new Intl.NumberFormat("pl-PL").format(n)+" zł";const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};function save(){localStorage.setItem("aurelia-cart",JSON.stringify(state.cart));renderCart()}function renderCart(){const c=$("#cartCount"),items=$("#cartItems"),total=$("#cartTotal");c.textContent=state.cart.length;total.textContent=money(state.cart.reduce((a,p)=>a+p.price,0));if(!state.cart.length){items.innerHTML='<p class="empty-cart">Twoja torba jest jeszcze pusta.</p>';return}items.innerHTML=state.cart.map((p,i)=>'<div class="cart-row"><img class="cart-thumb" src="'+p.img+'" alt=""><div><h4>'+p.name+'</h4><p>'+money(p.price)+'</p></div><button class="remove-item" data-remove="'+i+'">×</button></div>').join("");$$("[data-remove]").forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);save()})}$$(".add-product").forEach(btn=>btn.onclick=()=>{const card=btn.closest(".product-card");state.cart.push({name:card.dataset.name,price:+card.dataset.price,img:$("img",card).src});save();toast("Dodano do torby");btn.textContent="Dodano ✓";setTimeout(()=>btn.textContent="Dodaj do torby",1000)});renderCart();

const drawer=$("#cartDrawer"),backdrop=$("#backdrop");function openCart(){drawer.classList.add("open");backdrop.classList.add("open");document.body.classList.add("no-scroll")}function closeCart(){drawer.classList.remove("open");backdrop.classList.remove("open");document.body.classList.remove("no-scroll")}$$("[data-open-cart]").forEach(b=>b.onclick=openCart);$$("[data-close-cart]").forEach(b=>b.onclick=closeCart);backdrop.onclick=closeCart;

const search=$("#searchOverlay"),input=$("#searchInput"),result=$("#searchResult");function openSearch(){search.classList.add("open");input.focus();document.body.classList.add("no-scroll")}function closeSearch(){search.classList.remove("open");document.body.classList.remove("no-scroll")}$$("[data-open-search]").forEach(b=>b.onclick=openSearch);$$("[data-close-search]").forEach(b=>b.onclick=closeSearch);input.oninput=()=>{const q=input.value.toLowerCase().trim();if(!q){result.textContent="Wpisz nazwę produktu lub kategorię.";return}const matches=$$(".product-card").filter(c=>(c.dataset.name+" "+c.dataset.category).toLowerCase().includes(q));result.textContent=matches.length?"Znaleziono "+matches.length+" pasujący produkt.":"Nie znaleziono produktu — spróbuj innej frazy.";};

const menu=$("#mobileMenu");$("[data-menu]").onclick=()=>menu.classList.toggle("open");$$(".mobile-menu a").forEach(a=>a.onclick=()=>menu.classList.remove("open"));

$$(".heart").forEach(b=>b.onclick=()=>{b.classList.toggle("active");b.textContent=b.classList.contains("active")?"♥":"♡";toast(b.classList.contains("active")?"Dodano do ulubionych":"Usunięto z ulubionych")});

const filters=$("#filters");$("[data-filter-toggle]").onclick=()=>filters.classList.toggle("show");$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");const f=b.dataset.filter;$$(".product-card").forEach(c=>{c.style.display=f==="all"||c.dataset.category===f?"":"none"})});

const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});$$(".reveal").forEach(e=>observer.observe(e));

const viewer=$("#viewer"),model=$(".chair-3d");let dragging=false,lastX=0,rotation=-15;const move=x=>{if(!dragging)return;rotation+=(x-lastX)*.45;lastX=x;model.style.transform='translate(-50%,-45%) rotateY('+rotation+'deg)'};viewer.onpointerdown=e=>{dragging=true;lastX=e.clientX;viewer.setPointerCapture(e.pointerId)};viewer.onpointermove=e=>move(e.clientX);viewer.onpointerup=()=>dragging=false;viewer.onpointercancel=()=>dragging=false;

$("#newsletterForm").onsubmit=e=>{e.preventDefault();e.target.innerHTML='<p class="newsletter-message">Gotowe — sprawdź swoją skrzynkę. ✦</p>';toast("Dziękujemy za zapis!");};document.querySelector(".checkout").onclick=()=>toast(state.cart.length?"Demo sklepu — formularz zamówienia możemy dodać w kolejnym kroku.":"Najpierw dodaj coś do torby.");